# Generated by Django 5.1.4 on 2026-06-24 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('participantes_max', models.IntegerField(default=0)),
                ('imagen_url', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cientifico', models.CharField(max_length=200)),
                ('nombre_comun', models.CharField(max_length=200)),
                ('familia', models.CharField(max_length=100)),
                ('imagen_url', models.CharField(max_length=500)),
                ('parte_utilizada', models.TextField()),
                ('propiedades_usos', models.TextField()),
                ('posologia', models.TextField()),
                ('efectos_adversos', models.TextField(blank=True, null=True)),
                ('interacciones', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantas', to='fitoterapia.categoria')),
            ],
        ),
    ]
